#!/bin/bash

# Author: chenqiliang@xiaomi.com
# NOTE: log file format
#  Save to logfile in /data/soft/monitor/os-YYYY-MM-DD@HOSTNAME

#[Monitor] >>: YYYY-MM-DD HH:MI:SS  ## Start a monitor
#>>>> SECTION_NAME                 ## 4 ">" means start of section
#SECTION DATA
#<<<< SECTION_NAME                 ## 4 "<" means end of section
# <empty line for seperation>      ## Optional
# ...                              ## Other sections
#[Monitor] <<: YYYY-MM-DD HH:MI:SS  ## End of a monitor

datestr=`date +"%Y-%m-%d"`
host=`hostname`
filename=/data/soft/monitor/os-$datestr@$host
datetimestr=`date +"%Y-%m-%d %H:%M:%S"`
echo "[Monitor] >>:$datetimestr"  >> $filename
echo ">>>> Process $datetimestr" >> $filename
ps -eo pid,user,pcpu,pmem,vsz,cmd,args | sort -rn -k 5  >> $filename
echo "<<<< Process $datetimestr"  >> $filename
echo "" >> $filename

echo ">>>> TOP $datetimestr" >> $filename
/usr/bin/top c n 1 b  >> $filename
echo "<<<< TOP $datetimestr" >> $filename

echo ">>>> FreeMemory $datetimestr" >> $filename
free -g >> $filename
echo "<<<< FreeMemory $datetimestr" >> $filename
echo "" >> $filename

CTL_FILES=`find /opt/soft/ -name 'xiaomimqctl' |grep '/xiaomi/sbin/'| grep -v sns |grep -v back |sort `
for CTL_FILE in $CTL_FILES
do
	echo "## checking xmq $CTL_FILE $datetimestr" >> $filename
	echo ">>>> XmqStatus" >> $filename
	$CTL_FILE status >> $filename
	echo "<<<< XmqStatus $datetimestr" >> $filename

	echo ">>>> XmqClusterStatus $datetimestr" >> $filename
	$CTL_FILE cluster_status >> $filename
	echo "<<<< XmqClusterStatus $datetimestr" >> $filename
done
echo "" >> $filename
CTL_FILES=`find /opt/soft/ |grep ejabberdctl |grep '/jabber3/sbin'`
CHIDS="2 5"
for CTL_FILE in $CTL_FILES
do
	echo "## checking ejabberd $CTL_FILE"  >> $filename
        echo ">>>> EjabberdStatus $datetimestr" >> $filename
        $CTL_FILE status >> $filename
        echo "<<<< EjabberdStatus $datetimestr" >> $filename

	for CHID in $CHIDS
        do
		    #echo ">>>> EjabberdConnectedUsers $CHID" >> $filename
        	#$CTL_FILE connected_users_number $CHID >> $filename
        	#echo "<<<< EjabberdConnectedUsers $CHID" >> $filename
            sleep 1
	    done
done
echo "" >> $filename
echo ">>>> IOSTAT $datetimestr" >> $filename
iostat -d -x  >> $filename
echo "<<<< IOSTAT $datetimestr" >> $filename
echo "" >> $filename
echo ">>>> SocketSumary $datetimestr" >> $filename
/usr/sbin/ss -s  >> $filename
echo "<<<< SocketSumary $datetimestr" >> $filename


echo "[Monitor] <<:" `date +"%Y-%m-%d %H:%M:%S"`  >> $filename
echo "" >> $filename
